server:
    port: 8888

spring:
  data:
    jdbc:
      repositories:
        enabled: false
  jmx:
    enabled: false
  jpa:
    showSql: true
    formatSql: true
    hibernate:
      ddlAuto: true
      namingStrategy : org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      physicalNamingStrategy : it.CustomPhysicalNamingStrategyImpl
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: twgdhitest@gmail.com
    password: xxxxxxxxx
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true
    locations:classpath: db/migration
    out-of-order: true
    table: schema_version
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
db:
  url: ${DB_URL:jdbc:postgresql://localhost:5432/gdhi}
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  username: ${DB_USERNAME:gdhi}
  password: ${DB_PASSWORD:password}
  driverClassName: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

endpoints.info.id: ping
endpoints.info.sensitive: false
endpoints.info.enabled: true
info.AppName: GDHI-Service
info.Description: Application Health Checker
info.body: pong
info.status: 200
aws:
  region:  ${AWS_REGION}
  bedrock:
    agentId: ${AWS_BEDROCK_AGENT_ID:}
    agentAliasId: ${AWS_BEDROCK_AGENT_ALIAS_ID:}
    agents:
      en:
        agentId: ${AWS_BEDROCK_EN_AGENT_ID:${AWS_BEDROCK_AGENT_ID:}}
        agentAliasId: ${AWS_BEDROCK_EN_AGENT_ALIAS_ID:${AWS_BEDROCK_AGENT_ALIAS_ID:}}
      es:
        agentId: ${AWS_BEDROCK_ES_AGENT_ID:}
        agentAliasId: ${AWS_BEDROCK_ES_AGENT_ALIAS_ID:}
      ar:
        agentId: ${AWS_BEDROCK_AR_AGENT_ID:}
        agentAliasId: ${AWS_BEDROCK_AR_AGENT_ALIAS_ID:}
      pt:
        agentId: ${AWS_BEDROCK_PT_AGENT_ID:}
        agentAliasId: ${AWS_BEDROCK_PT_AGENT_ALIAS_ID:}
      fr:
        agentId: ${AWS_BEDROCK_FR_AGENT_ID:}
        agentAliasId: ${AWS_BEDROCK_FR_AGENT_ALIAS_ID:}

frontEndURL: http://localhost:8080

mailer:
  addressMap:
    pavikrish2988@gmail.com: Name1

logging:
  level:
    root: info
  path: logs
  file: gdhi.log
  config: logback-spring.xml
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

excelFileLocation: "/opt/files/Digital Health Data.xlsx"
csvFileLocation: "/opt/files/Upload_template_Final.xlsx"
