version: 0.0
os: linux
files:
  - source: .
    destination: .
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 700
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 700
      runas: root


