ALTER TABLE country_health_data.country_summary DROP COLUMN data_collector_name;
ALTER TABLE country_health_data.country_summary DROP COLUMN data_collector_role;
ALTER TABLE country_health_data.country_summary DROP COLUMN data_collector_email;
