UPDATE master.health_indicators SET definition='Is digital health included and budgeted for in national health or relevant national strategies and/or plan(s)? Note: The focus of this indicator is on the inclusion of digital health or eHealth in the national health strategy.' where indicator_id=2;
UPDATE master.health_indicators SET definition='Is public funding (including loans) for digital health sufficient for the digital health strategies, priorities (needs), or costed-plan of the country?' where indicator_id=4;
UPDATE master.health_indicators SET definition='Is there a law on data security (across the full data lifecycle e.g. collection, processing, storage, transmission, use and destruction) that is relevant to digital health?' where indicator_id=5;
UPDATE master.health_indicators SET definition='Are there protocols, policies, frameworks or accepted processes governing the clinical and patient care use of connected medical devices and health services (e.g. telemedicine, applications), particularly in relation to safety, data integrity and quality of care- including provisions for AI and algorithms (at higher stages of maturity)?' where indicator_id=7;
UPDATE master.health_indicators SET definition='Are there protocols, policies, frameworks or accepted processes in place to support secure cross-border data exchange and storage in support of public health goals while protecting individual privacy? Note: This includes health-related data coming into a country, going out of a country, and/or being used in a country related to an individual from another country.' where indicator_id=8;
UPDATE master.health_indicators SET definition='Extract the Portuland institute technology pillar of network network readiness index score (https://networkreadinessindex.org )' where indicator_id=15;
UPDATE master.health_indicators SET definition='Is there an articulated plan for supporting the expansion of digital health infrastructure (including equipment- computers/ tablets/ phones, supplies, software, devices, etc.) provision and maintenance to all public healthcare facilities?' where indicator_id=16;
UPDATE master.health_indicators SET definition='Public sector priorities are supported by nationally-scaled digital health systems' where indicator_id=17;
UPDATE master.health_indicators SET definition='Are health system registries of uniquely identifiable providers, administrators, and public facilities (and private if applicable) available, accessible and current? Is the data geotagged to enable GIS mapping with protocols in place to protect sensitive datasets?' where indicator_id=18;
UPDATE master.health_indicators SET definition='Are secure registries or a master patient index of uniquely identifiable individuals available, fully representative of the population, accessible and current for use for health-related purposes?' where indicator_id=19;

