--- Questions ----

UPDATE i18n.health_indicator SET definition='هل يوجد في الدولة إدارة / وكالة / مجموعة عمل وطنية منفصلة للصحة الرقمية؟' where indicator_id=1 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل الصحة الرقمية مدرجة في الميزانية ولها مخصصات ضمن إطار الصحة الوطنية أو الاستراتيجيات و/أو الخطط الوطنية ذات الصلة؟ ملاحظة: ينصب التركيز في هذا المؤشر على إدراج الصحة الرقمية أو الصحة الإلكترونية في الاستراتيجية الوطنية للصحة.' where indicator_id=2 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل لدى الدولة استراتيجية أو إطار عمل للصحة الإلكترونية أو الصحة الرقمية وخطة للصحة الرقمية بتكلفة معينة؟' where indicator_id=3 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل التمويل العام (بما في ذلك القروض) للصحة الرقمية كاف لاستراتيجيات الصحة الرقمية أو الأولويات (الاحتياجات) أو الخطة محددة التكاليف للبلد؟' where indicator_id=4 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل هناك قانون بشأن أمن البيانات (عبر دورة حياة البيانات الكاملة مثل الجمع والمعالجة والتخزين والنقل والاستخدام والإتلاف) ذات الصلة بالصحة الرقمية؟' where indicator_id=5 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل هناك قانون لحماية خصوصية الأفراد، يحكم الملكية والموافقة والوصول ومشاركة البيانات الصحية الرقمية التي يمكن من خلالها التعرُف على هوية أصحابها؟' where indicator_id=6 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل هناك بروتوكولات أو سياسات أو أطر أو عمليات معتمدة تحكم استخدام الأجهزة الطبية والخدمات الصحية ذات العلاقة (مثل الطب الاتصالي والتطبيقات) في الرعاية السريرية ورعاية المرضى، لا سيما فيما يتعلق بالسلامة وسلامة البيانات وجودة الرعاية - بما في ذلك أحكام الذكاء الاصطناعي والخوارزميات (في مراحل متقدمة من الاكتمال)؟' where indicator_id=7 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل هناك بروتوكولات أو سياسات أو أطر أو عمليات معتمدة لدعم التبادل الآمن للبيانات عبر الحدود وتخزينها لدعم أهداف الصحة العامة مع حماية خصوصية الأفراد؟ ملاحظة: يتضمن ذلك البيانات المتعلقة بالصحة والواردة إلى بلد ما، و / أو الخارجة من بلد ما، و / أو المستخدمة في بلد لمصلحة شخص من بلد آخر.' where indicator_id=8 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل تمثل الصحة الرقمية جزء من المناهج الدراسية المستخدمة في تدريب متخصصي الدعم الصحي والخدمات المساندة بشكل عام؟' where indicator_id=9 and language_id='ar';
UPDATE i18n.health_indicator SET definition='على وجه التحديد، هل الصحة الرقمية جزء من المناهج الدراسية للمختصين في الدعم الصحي ضمن القوى العاملة بشكل عام؟ [يُعّرف هؤلاء بأنهم العاملون الصحيون المجتمعيون والممرضين والأطباء والمهن الصحية المساعدة ومديرو / إداريو الصحة والفنيون]' where indicator_id=10 and language_id='ar';
UPDATE i18n.health_indicator SET definition='بشكل عام، هل يتخرج عاملون مدربون في الصحة الرقمية من برامج التدريب المطروحة في إطار الحصول على الدرجة الجامعية الأولى في الصحة الرقمية / المعلوماتية الصحية / نظم المعلومات الصحية / المعلوماتية الطبية الحيوية (في المؤسسات العامة أو الخاصة)؟ ' where indicator_id=11 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل هناك مسميات وظيفية ومسارات مهنية للقطاع العام في مجال الصحة الرقمية' where indicator_id=12 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل يوجد إطار هيكلي وطني للصحة الرقمية (الصحة الإلكترونية) و / أو تبادل المعلومات الصحية (HIE)؟' where indicator_id=13 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل توجد معايير معلومات الصحة / الصحة الرقمية لتبادل البيانات ونقلها والرسائل والأمن والخصوصية والأجهزة' where indicator_id=14 and language_id='ar';
UPDATE i18n.health_indicator SET definition='استخراج الركيزة التكنولوجية لمعهد بورتولاند من درجة مؤشر جاهزية الشبكة (https://networkreadinessindex.org )' where indicator_id=15 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل هناك خطة واضحة لدعم البنية التحتية للصحة الرقمية (بما في ذلك المعدات - أجهزة الكمبيوتر / الأجهزة اللوحية / الهواتف، اللوازم، البرامج، الأجهزة، إلخ) وتوفيرها وصيانتها؟' where indicator_id=16 and language_id='ar';
UPDATE i18n.health_indicator SET definition='يتم دعم أولويات القطاع العام من خلال أنظمة الصحة الرقمية ذات النطاق الوطني.' where indicator_id=17 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل سجلات النظام الصحي لمزودي الخدمات والمسؤولين والمرافق العامة (والخاصة إذا كان ذلك ممكنًا) التي يمكن تحديدها بشكل فريد متوفرة ومتاحة وحديثة؟ هل تم وضع علامات جغرافية على البيانات لتمكين نظم المعلومات الجغرافية مع توفر بوتوكولات لحماية المعلومات الحساسة' where indicator_id=18 and language_id='ar';
UPDATE i18n.health_indicator SET definition='هل السجلات الآمنة أو فهرس المريض الرئيسي للأفراد الذين يمكن التعرف عليهم بشكل فريد متاحة ويمكن الوصول إليها ومحدثة للاستخدام لأغراض تتعلق بالصحة' where indicator_id=19 and language_id='ar';
UPDATE i18n.health_indicator SET definition='على وجه التحديد، هل يوجد سجل شامل آمن للمرضى يتيح تحديد كل منهم بشكل فردي، وهو متاح ويمكن الوصول إليه وحديث للاستخدام في الأغراض المتعلقة بالصحة؟' where indicator_id=27 and language_id='ar';
UPDATE i18n.health_indicator SET definition='على وجه التحديد، هل هناك سجل آمن للمواليد يتيح تحديد كل منهم بشكل فردي، ومتاح ويمكن الوصول إليه وحديث للاستخدام لأغراض تتعلق بالصحة؟ ' where indicator_id=28 and language_id='ar';
UPDATE i18n.health_indicator SET definition='على وجه التحديد، هل هناك سجل آمن للوفيات يتيح تحديد كل منهم بشكل فردي، ومتاح ويمكن الوصول إليه وحديث للاستخدام لأغراض تتعلق بالصحة؟ ' where indicator_id=29 and language_id='ar';


UPDATE i18n.health_indicator SET definition='O país tem um departamento/agência/grupo de trabalho nacional separado para saúde digital?' where indicator_id=1 and language_id='pt';
UPDATE i18n.health_indicator SET definition='A saúde digital está incluída e orçada na saúde nacional ou nas estratégias e/ou planos nacionais relevantes? Nota: O foco deste indicador é a inclusão da saúde digital ou eHealth na estratégia nacional de saúde.' where indicator_id=2 and language_id='pt';
UPDATE i18n.health_indicator SET definition='O país tem uma estratégia ou estrutura de eSaúde ou saúde digital e um plano de saúde digital custeado?' where indicator_id=3 and language_id='pt';
UPDATE i18n.health_indicator SET definition='O financiamento público (incluindo empréstimos) para saúde digital é suficiente para as estratégias de saúde digital, prioridades (necessidades) ou plano custeado do país?' where indicator_id=4 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Existe uma lei sobre segurança de dados (em todo o ciclo de vida dos dados, por exemplo, coleta, processamento, armazenamento, transmissão, uso e destruição) que seja relevante para a saúde digital?' where indicator_id=5 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Existe uma lei para proteger a privacidade individual, regendo a propriedade, consentimento, acesso e compartilhamento de dados de saúde digitais identificáveis individualmente?' where indicator_id=6 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Existem protocolos, políticas, estruturas ou processos aceitos que regem o uso clínico e de atendimento ao paciente de dispositivos médicos e serviços de saúde conectados (por exemplo, telemedicina, aplicativos), particularmente em relação à segurança, integridade dos dados e qualidade do atendimento, incluindo provisões para IA e algoritmos (em estágios mais altos de maturidade)?' where indicator_id=7 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Existem protocolos, políticas, estruturas ou processos aceitos em vigor para oferecer suporte à troca e armazenamento seguro de dados transfronteiriços para apoiar as metas de saúde pública e, ao mesmo tempo, proteger a privacidade individual? Nota: Isso inclui dados relacionados à saúde entrando em um país, saindo de um país e/ou sendo usados em um país relacionado a um indivíduo de outro país.' where indicator_id=8 and language_id='pt';
UPDATE i18n.health_indicator SET definition='A saúde digital faz parte do currículo dos profissionais de saúde e de apoio à saúde em formação, em geral?' where indicator_id=9 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Especificamente, a saúde digital faz parte do currículo para profissionais de saúde e de suporte relacionados à saúde na força de trabalho em geral? [Definido como agentes comunitários de saúde, enfermeiros, médicos, profissionais de saúde, gerentes/administradores de saúde e tecnólogos]' where indicator_id=10 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Em geral, o treinamento em programas de graduação em saúde digital/informática em saúde/sistemas de informação em saúde/informática biomédica (em instituições públicas ou privadas) está produzindo profissionais de saúde digital treinados?' where indicator_id=11 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Existem títulos profissionais do setor público e planos de carreira em saúde digital?' where indicator_id=12 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Existe uma estrutura arquitetônica nacional de saúde digital (eHealth) e/ou troca de informações de saúde (HIE) estabelecida?' where indicator_id=13 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Existem padrões digitais de saúde/informações de saúde para troca de dados, transmissão, mensagens, segurança, privacidade e hardware?' where indicator_id=14 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Extraia o pilar de tecnologia do Instituto Portuland da pontuação do índice de prontidão de rede (https://networkreadinessindex.org )' where indicator_id=15 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Existe um plano articulado para apoiar a expansão da infraestrutura de saúde digital (incluindo equipamentos- computadores/tablets/telefones, suprimentos, software, dispositivos, etc.) fornecimento e manutenção para todas as unidades de saúde pública?' where indicator_id=16 and language_id='pt';
UPDATE i18n.health_indicator SET definition='As prioridades do setor público são apoiadas por sistemas digitais de saúde em escala naciona l' where indicator_id=17 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Os registros do sistema de saúde de provedores, administradores e estabelecimentos públicos (e privados, se aplicável) identificáveis de forma única estão disponíveis, acessíveis e atualizados? Os dados são marcados geograficamente para permitir o mapeamento GIS com protocolos em vigor para proteger conjuntos de dados confidenciais?' where indicator_id=18 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Existem registros seguros ou um índice mestre de pacientes de indivíduos identificáveis de forma única, totalmente representativos da população, acessíveis e atualizados para uso para fins relacionados à saúde?' where indicator_id=19 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Especificamente, existe um índice mestre de pacientes seguro de indivíduos exclusivamente identificáveis disponível, acessível e atual para uso para fins relacionados à saúde?' where indicator_id=27 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Especificamente, existe um registro de nascimento seguro de indivíduos identificáveis de forma única disponível, acessível e atual para uso para fins relacionados à saúde?' where indicator_id=28 and language_id='pt';
UPDATE i18n.health_indicator SET definition='Especificamente, existe um registro seguro de óbitos de indivíduos identificáveis de forma única disponível, acessível e atual para uso para fins relacionados à saúde?' where indicator_id=29 and language_id='pt';


UPDATE i18n.health_indicator SET definition='¿Tiene el país un departamento/agencia/grupo de trabajo nacional separado para la salud digital?' where indicator_id=1 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿La salud digital está incluida y presupuestada en la estrategia de salud nacional  y/o planes nacionales pertinentes? Nota: El enfoque de este indicador está en la inclusión de la salud digital o eSalud en la estrategia nacional de salud.' where indicator_id=2 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Cuenta el país con una estrategia o marco de eSalud o salud digital y un plan de salud digital presupuestado?' where indicator_id=3 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿La financiación pública (incluidos los préstamos) para la salud digital es suficiente para la estrategia de salud digital, las prioridades (necesidades) o el plan presupuestario del país?' where indicator_id=4 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Existe una ley sobre la seguridad de los datos (a lo largo de todo el ciclo de vida de los datos, por ejemplo, recopilación, procesamiento, almacenamiento, transmisión, uso y destrucción) que sea relevante para la salud digital?' where indicator_id=5 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Existe una ley para proteger la privacidad individual, que rija la propiedad, el consentimiento, el acceso y el intercambio de datos de salud digitales identificables individualmente?' where indicator_id=6 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Existen protocolos, políticas, marcos o procesos aceptados que rijan el uso clínico y de atención al paciente de dispositivos médicos y servicios de salud conectados (p. ej., telemedicina, aplicaciones), particularmente en relación con la seguridad, la integridad de los datos y la calidad de la atención, incluidas las disposiciones para IA y algoritmos? (en etapas más altas de madurez)?' where indicator_id=7 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Existen protocolos, políticas, marcos o procesos aceptados para respaldar el intercambio y el almacenamiento de datos transfronterizos seguros en apoyo de los objetivos de salud pública mientras se protege la privacidad individual? Nota: Esto incluye datos relacionados con la salud que ingresan a un país, salen de un país y/o se usan en un país en relación con una persona de otro país.' where indicator_id=8 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿La salud digital forma parte del currículo de los profesionales de la salud y de apoyo a la salud en formación, en general?' where indicator_id=9 and language_id='es';
UPDATE i18n.health_indicator SET definition='Específicamente, ¿la salud digital es parte del plan de estudios para los profesionales de la salud y de apoyo relacionados con la salud en el recurso humano en general? [Definidos como trabajadores de salud comunitarios, enfermeras, médicos, auxiliares de salud, gerentes/administradores de salud y tecnólogos]' where indicator_id=10 and language_id='es';
UPDATE i18n.health_indicator SET definition='En general, ¿la formación en salud digital/informática sanitaria/sistemas de información sanitaria/programas de grado en informática biomédica (ya sea en instituciones públicas o privadas) está produciendo trabajadores capacitados en salud digital?' where indicator_id=11 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Existen títulos profesionales y carreras profesionales en salud digital del sector público?' where indicator_id=12 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Existe un marco arquitectónico nacional de salud digital (eHealth) y/o un intercambio de información de salud (HIE) establecido?' where indicator_id=13 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Existen estándares de información de salud/salud digital para el intercambio de datos, transmisión, mensajería, seguridad, privacidad y hardware?' where indicator_id=14 and language_id='es';
UPDATE i18n.health_indicator SET definition='Extraiga la puntuación del índice de disponibilidad de la red del pilar tecnológico del instituto Portuland (https://networkreadinessindex.org )' where indicator_id=15 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Existe un plan articulado para apoyar la expansión de la infraestructura de salud digital (incluidos los equipos, computadoras/tabletas/teléfonos, suministros, software, dispositivos, etc.), provisión y mantenimiento para todas las instalaciones de salud pública?' where indicator_id=16 and language_id='es';
UPDATE i18n.health_indicator SET definition='Las prioridades del sector público están respaldadas por sistemas de salud digitales a escala naciona l' where indicator_id=17 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Están disponibles, accesibles y actualizados los registros del sistema de salud de proveedores, administradores y establecimientos públicos (y privados, si corresponde) identificables de manera única? ¿Los datos están geoetiquetados para permitir el mapeo GIS con protocolos implementados para proteger conjuntos de datos confidenciales?' where indicator_id=18 and language_id='es';
UPDATE i18n.health_indicator SET definition='¿Están disponibles registros seguros o un índice maestro de pacientes de individuos identificables de manera única, totalmente representativos de la población, accesibles y actualizados para su uso con fines relacionados con la salud?' where indicator_id=19 and language_id='es';
UPDATE i18n.health_indicator SET definition='Específicamente, ¿hay un índice maestro de pacientes seguro de individuos identificables de forma única disponible, accesible y actualizado para su uso con fines relacionados con la salud?' where indicator_id=27 and language_id='es';
UPDATE i18n.health_indicator SET definition='Específicamente, ¿hay un registro de nacimiento seguro de individuos identificables de forma única disponible, accesible y actualizado para su uso con fines relacionados con la salud?' where indicator_id=28 and language_id='es';
UPDATE i18n.health_indicator SET definition='Específicamente, ¿hay un registro seguro de defunciones de personas identificables de forma única disponible, accesible y actualizado para su uso con fines relacionados con la salud?' where indicator_id=29 and language_id='es';



UPDATE i18n.health_indicator SET definition='Le pays dispose-t-il d''un département/agence/groupe de travail national distinct pour la santé numérique?' where indicator_id=1 and language_id='fr';
UPDATE i18n.health_indicator SET definition='La santé numérique est-elle incluse et budgétisée dans la politique nationale de santé ou les stratégies et/ou plans nationaux pertinents ? Remarque : Cet indicateur se concentre sur  l''inclusion de la santé numérique ou de la cybersanté dans la stratégie nationale de santé.' where indicator_id=2 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Le pays dispose-t-il d''une stratégie ou d''un cadre de cybersanté ou de santé numérique et d''un plan de santé numérique chiffré ?' where indicator_id=3 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Le financement public (y compris les prêts) pour la santé numérique est-il suffisant pour les stratégies, les priorités (besoins) ou le plan chiffré de santé numérique du pays ?' where indicator_id=4 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il une loi sur la sécurité des données (tout au long du cycle de vie des données, par exemple la collecte, le traitement, le stockage, la transmission,  l''utilisation et la destruction) qui concerne la santé numérique ?' where indicator_id=5 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il une loi pour protéger la vie privée des individus, régissant la propriété, le consentement,  l''accès et le partage des données de santé numériques identifiables individuellement ?' where indicator_id=6 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il des protocoles, des politiques, des cadres ou des processus acceptés régissant  l''utilisation clinique et des soins aux patients des dispositifs médicaux et des services de santé connectés (par exemple, la télémédecine, les applications), en particulier en ce qui concerne la sécurité,  l''intégrité des données et la qualité des soins, y compris des dispositions pour  l''IA et les algorithmes ? (à des stades de maturité plus élevés) ?' where indicator_id=7 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il des protocoles, des politiques, des cadres ou des processus acceptés en place pour soutenir  l''échange et le stockage de données transfrontaliers sécurisés à  l''appui des objectifs de santé publique tout en protégeant la vie privée des individus ? Remarque : Cela inclut les données relatives à la santé entrant dans un pays, sortant d''un pays et/ou utilisées dans un pays concernant une personne d''un autre pays.' where indicator_id=8 and language_id='fr';
UPDATE i18n.health_indicator SET definition='La santé numérique fait-elle partie du programme d''études pour les professionnels de la santé et de  l''assistance liée à la santé en formation, en général ?' where indicator_id=9 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Plus précisément, la santé numérique fait-elle partie du programme d''études pour les professionnels de la santé et du soutien lié à la santé dans la main-d''œuvre en général ? [Définis comme agents de santé communautaires, infirmières, médecins, personnel paramédical, gestionnaires/administrateurs de la santé et technologues]' where indicator_id=10 and language_id='fr';
UPDATE i18n.health_indicator SET definition='En général, la formation en santé numérique/informatique de santé/systèmes d''information de santé/programmes diplômants en informatique biomédicale (dans des établissements publics ou privés) produit-elle des agents de santé numériques formés ?' where indicator_id=11 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il des titres professionnels et des parcours professionnels publics en santé numérique ?' where indicator_id=12 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il un cadre architectural national de santé numérique (eHealth) et/ou d''échange d''informations sur la santé (HIE) ?' where indicator_id=13 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il des normes numériques sur la santé/ l''information sur la santé pour  l''échange de données, la transmission, la messagerie, la sécurité, la confidentialité et le matériel ?' where indicator_id=14 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Extraire le pilier technologique de  l''institut Portuland du score de  l''indice de préparation du réseau(https://networkreadinessindex.org )' where indicator_id=15 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il un plan articulé pour soutenir  l''expansion de  l''infrastructure de santé numérique (y compris  l''équipement - ordinateurs/tablettes/téléphones, fournitures, logiciels, appareils, etc.) la fourniture et la maintenance de tous les établissements de santé publics ?' where indicator_id=16 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Les priorités du secteur public sont soutenues par des systèmes de santé numériques à  l''échelle nationale' where indicator_id=17 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Les registres du système de santé des prestataires, administrateurs et établissements publics identifiables de manière unique (et privés le cas échéant) sont-ils disponibles, accessibles et à jour ? Les données sont-elles géolocalisées pour permettre la cartographie SIG avec des protocoles en place pour protéger les ensembles de données sensibles ?' where indicator_id=18 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il des registres sécurisés ou un fichier principal des patients d''individus identifiables de manière unique, pleinement a de la population, accessibles et à jour pour une utilisation à des fins liées à la santé ?' where indicator_id=19 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Plus précisément, existe-t-il un fichier principal sécurisé des patients d''individus identifiables de manière unique disponible, accessible et à jour pour une utilisation à des fins liées à la santé ?' where indicator_id=27 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Plus précisément, existe-t-il un registre des naissances sécurisé d''individus identifiables de manière unique, disponible, accessible et à jour pour une utilisation à des fins liées à la santé ?' where indicator_id=28 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Plus précisément, existe-t-il un registre sécurisé des décès d''individus identifiables de manière unique, disponible, accessible et à jour pour une utilisation à des fins liées à la santé ?' where indicator_id=29 and language_id='fr';