ALTER TABLE i18n.category SET name = 'Leadership & Gouvernance' where category_id=1 and language_id='fr';
ALTER TABLE i18n.category SET name = 'Liderança e Governança' where category_id=1 and language_id='pt';
ALTER TABLE i18n.category SET name = 'Stratégie & investissement' where category_id=2 and language_id='fr';
ALTER TABLE i18n.category SET name = 'Législation, politique & conformité' where category_id=3 and language_id='fr';
ALTER TABLE i18n.category SET name = 'القوي العاملة' where category_id=4 and language_id='ar';
ALTER TABLE i18n.category SET name = 'trabalhadores' where category_id=4 and language_id='pt';
ALTER TABLE i18n.category SET name = 'Standards/ Normes & Interoperabilité' where category_id=5 and language_id='fr';
ALTER TABLE i18n.category SET name = 'Padrões e Interoperabilidade' where category_id=5 and language_id='pt';
ALTER TABLE i18n.category SET name = 'A infraestrutura' where category_id=6 and language_id='pt';
ALTER TABLE i18n.category SET name = 'Services & Applications' where category_id=7 and language_id='fr';