UPDATE i18n.health_indicator SET definition='La santé numérique est-elle incluse et budgétisée dans la politique nationale de santé ou les stratégies et/ou plans nationaux pertinents? Remarque: Cet indicateur se concentre sur l''inclusion de la santé numérique ou de la cybersanté dans la stratégie nationale de santé.' where indicator_id=2 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Le financement public (y compris les prêts) pour la santé numérique est-il suffisant pour les stratégies, les priorités (besoins) ou le plan chiffré de santé numérique du pays?' where indicator_id=4 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il une loi sur la sécurité des données (tout au long du cycle de vie des données, par exemple la collecte, le traitement, le stockage, la transmission, l''utilisation et la destruction) qui concerne la santé numérique?' where indicator_id=5 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il des protocoles, des politiques, des cadres ou des processus acceptés régissant l''utilisation clinique et des soins aux patients des dispositifs médicaux et des services de santé connectés (par exemple, la télémédecine, les applications), en particulier en ce qui concerne la sécurité, l''intégrité des données et la qualité des soins, y compris des dispositions pour l''IA et les algorithmes? (à des stades de maturité plus élevés)?' where indicator_id=7 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il des protocoles, des politiques, des cadres ou des processus acceptés en place pour soutenir l''échange et le stockage de données transfrontaliers sécurisés à l''appui des objectifs de santé publique tout en protégeant la vie privée des individus? Remarque: Cela inclut les données relatives à la santé entrant dans un pays, sortant d''un pays et/ou utilisées dans un pays concernant une personne d''un autre pays.' where indicator_id=8 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Extraire le pilier technologique de l''institut Portuland du score de l''indice de préparation du réseau(https://networkreadinessindex.org )' where indicator_id=15 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il un plan articulé pour soutenir l''expansion de l''infrastructure de santé numérique (y compris l''équipement - ordinateurs/tablettes/téléphones, fournitures, logiciels, appareils, etc.) la fourniture et la maintenance de tous les établissements de santé publics?' where indicator_id=16 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Les priorités du secteur public sont soutenues par des systèmes de santé numériques à l''échelle nationale' where indicator_id=17 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Les registres du système de santé des prestataires, administrateurs et établissements publics identifiables de manière unique (et privés le cas échéant) sont-ils disponibles, accessibles et à jour? Les données sont-elles géolocalisées pour permettre la cartographie SIG avec des protocoles en place pour protéger les ensembles de données sensibles?' where indicator_id=18 and language_id='fr';
UPDATE i18n.health_indicator SET definition='Existe-t-il des registres sécurisés ou un fichier principal des patients d''individus identifiables de manière unique, pleinement représentatifs de la population, accessibles et à jour pour une utilisation à des fins liées à la santé?' where indicator_id=19 and language_id='fr';


