UPDATE i18n.score_definition SET definition = 'Il n''y a pas de protocoles, de politiques, de cadres ou de processus acceptés en place pour soutenir l''échange et le stockage de données transfrontaliers sécurisés à l''appui des objectifs de santé publique tout en protégeant la vie privée des individus.' WHERE indicator_id =8 AND score =1 AND language_id = 'fr';
UPDATE i18n.score_definition SET definition = 'Des protocoles, des politiques, des cadres ou des processus acceptés pour l''échange et le stockage transfrontaliers de données à l''appui des objectifs de santé publique tout en protégeant la vie privée des individus ont été proposés et sont en cours d''examen.' WHERE indicator_id =8 AND score =2 AND language_id = 'fr';
UPDATE i18n.score_definition SET definition = 'Des protocoles, des politiques, des cadres ou des processus acceptés pour l''échange et le stockage transfrontaliers de données à l''appui des objectifs de santé publique tout en protégeant la vie privée des individus ont été adoptés, mais ne sont pas entièrement mis en œuvre.' WHERE indicator_id =8 AND score =3 AND language_id = 'fr';
UPDATE i18n.score_definition SET definition = 'Des protocoles, des politiques, des cadres ou des processus acceptés pour l''échange et le stockage transfrontaliers de données à l''appui des objectifs de santé publique tout en protégeant la vie privée des individus ont été mis en œuvre, mais pas systématiquement appliqués.' WHERE indicator_id =8 AND score =4 AND language_id = 'fr';
UPDATE i18n.score_definition SET definition = 'Les protocoles, politiques, cadres ou processus acceptés pour l''échange et le stockage transfrontaliers de données à l''appui des objectifs de santé publique tout en protégeant la vie privée des individus ont été mis en œuvre et appliqués de manière cohérente.' WHERE indicator_id =8 AND score =5 AND language_id = 'fr';

UPDATE i18n.score_definition SET definition = 'Il n''y a pas de programme de santé numérique dans le cadre de la formation continue (formation continue) pour les professionnels de la santé sur le marché du travail.' WHERE indicator_id =10 AND score =1 AND language_id = 'fr';
UPDATE i18n.score_definition SET definition = 'Programme de santé numérique proposé et en cours d''examen dans le cadre de la formation continue (formation continue) des professionnels de la santé en milieu de travail.' WHERE indicator_id =10 AND score =2 AND language_id = 'fr';
UPDATE i18n.score_definition SET definition = 'Le programme de santé numérique est mis en œuvre dans le cadre de la formation continue (formation continue) pour <50% des professionnels de la santé dans la population active.' WHERE indicator_id =10 AND score =3 AND language_id = 'fr';
UPDATE i18n.score_definition SET definition = 'Le programme de santé numérique est mis en œuvre dans le cadre de la formation continue (formation continue) pour 50 à 75% des professionnels de la santé au sein de la population active.' WHERE indicator_id =10 AND score =4 AND language_id = 'fr';
UPDATE i18n.score_definition SET definition = 'Le programme de santé numérique est mis en œuvre dans le cadre de la formation continue (formation continue) pour > 75% des professionnels de la santé dans la main-d''œuvre.' WHERE indicator_id =10 AND score =5 AND language_id = 'fr';

UPDATE i18n.score_definition SET definition = 'Necessidades de força de trabalho de saúde digital avaliadas, lacunas identificadas e opções de treinamento em desenvolvimento.' WHERE indicator_id =11 AND score =2 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'O treinamento profissional está disponível, mas os graduados ainda não foram implantados.' WHERE indicator_id =11 AND score =3 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'Profissionais de saúde digital treinados disponíveis e implantados, mas ainda há lacunas essenciais de pessoal.' WHERE indicator_id =11 AND score =4 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'Número suficiente de profissionais de saúde digital treinados disponíveis para atender às necessidades nacionais de saúde digital.' WHERE indicator_id =11 AND score =5 AND language_id = 'pt';

UPDATE i18n.score_definition SET definition = 'Nenhuma estratégia, política ou guia de força de trabalho que reconheça a saúde digital está em vigor. A distribuição da força de trabalho de saúde digital é ad hoc.' WHERE indicator_id =12 AND score =1 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'Uma avaliação nacional das necessidades mostra o número e os tipos de habilidades necessárias para apoiar a saúde digital com foco explícito no treinamento de profissionais de saúde do sexo feminino.' WHERE indicator_id =12 AND score =2 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'As funções e responsabilidades da equipe de saúde digital são mapeadas para a força de trabalho e esquemas de carreira do governo e 25-50% da força de trabalho de saúde digital necessária do setor público está em vigor.' WHERE indicator_id =12 AND score =3 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'Existe uma política de RH e um plano estratégico que identifica as habilidades e funções necessárias para apoiar a saúde digital com foco explícito no treinamento de profissionais de saúde do sexo feminino e uma estimativa de 50 a 75% da força de trabalho de saúde digital do setor público.' WHERE indicator_id =12 AND score =4 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'Existe um plano de longo prazo para aumentar e manter a equipe com as habilidades necessárias para sustentar a saúde digital nos níveis nacional e subnacional, com foco explícito no treinamento de quadros de trabalhadoras de saúde do sexo feminino com um número estimado de mais de 75% dos cargos necessários preenchidos. Os sistemas de gestão de desempenho estão em vigor para garantir o crescimento e a sustentabilidade da força de trabalho de saúde digital com oferta suficiente para atender às necessidades de saúde digital e pouca rotatividade de pessoal.' WHERE indicator_id =12 AND score =5 AND language_id = 'pt';

UPDATE i18n.score_definition SET definition = 'Não existe uma estrutura arquitetônica nacional de saúde digital (eHealth) e/ou troca de informações de saúde (HIE) estabelecida.' WHERE indicator_id =13 AND score =1 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'Uma arquitetura digital de saúde nacional e/ou troca de informações de saúde (HIE) foi proposta, mas não aprovada, incluindo camadas semânticas, sintáticas e organizacionais.' WHERE indicator_id =13 AND score =2 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'A arquitetura digital de saúde nacional e/ou troca de informações de saúde (HIE) é operável e fornece funções essenciais, como autenticação, tradução, armazenamento e função de armazenamento, guia para quais dados estão disponíveis e como acessá-los e interpretação de dados.' WHERE indicator_id =13 AND score =3 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'O governo lidera, gerencia e reforça a implementação da arquitetura digital de saúde nacional e/ou a troca de informações de saúde (HIE), que são totalmente implementadas de acordo com os padrões da indústria.' WHERE indicator_id =13 AND score =4 AND language_id = 'pt';
UPDATE i18n.score_definition SET definition = 'A arquitetura digital de saúde nacional e/ou troca de informações de saúde (HIE) fornece funções básicas de troca de dados e é revisada e atualizada periodicamente para atender às necessidades da arquitetura digital de saúde em constante mudança. Há aprendizado contínuo, inovação e controle de qualidade. Os dados são usados ativamente para planejamento e orçamento estratégico nacional de saúde.' WHERE indicator_id =13 AND score =5 AND language_id = 'pt';

UPDATE i18n.score_definition SET definition='La estrategia nacional de salud digital y el plan presupuestario se implementaron por completo con planificación en curso para el próximo ciclo de 3 a 5 años.' where indicator_id=3 and score=5 and language_id='es';

UPDATE i18n.score_definition SET definition='تم تنفيذ الاستراتيجية الوطنية للصحة الرقمية وخطة التكلفة بالكامل مع التخطيط الجاري للدروة القادمة لمدة 3-5 سنوات.' where indicator_id=3 and score=5 and language_id='ar';
