INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30,-1,  'pt', 'Não disponível');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 1,  'pt', 'As políticas nacionais de transformação digital e governança de dados não incluem benefícios e riscos potenciais para a saúde pública ou resultados individuais de saúde.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 2,  'pt', 'As políticas nacionais de transformação digital e governança de dados incluem potenciais benefícios e riscos para a saúde pública ou resultados individuais de saúde em uma base ad hoc.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 3,  'pt', 'As políticas nacionais de transformação digital e governança de dados incluem sistematicamente benefícios e riscos potenciais para a saúde pública ou resultados individuais de saúde, mas não têm estratégia(s) para abordá-los.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 4,  'pt', 'As políticas nacionais de transformação digital e governança de dados incluem sistematicamente benefícios e riscos potenciais para a saúde pública ou resultados individuais de saúde e têm algumas estratégias para abordá-los que ainda não foram implementadas.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 5,  'pt', 'Todas as políticas relevantes de transformação digital e governança de dados consideram os potenciais benefícios e riscos para os sistemas de saúde, determinantes da saúde e resultados individuais de saúde (incluindo para crianças, mulheres e grupos vulneráveis) e têm estratégias multissetoriais que são totalmente implementadas.');

INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31,-1,  'pt', 'Não disponível');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 1,  'pt', 'Não há nenhum plano de tecnologias emergentes (por exemplo, AI, Wearables, Blockchain, IoT) para apoiar as metas de saúde pública.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 2,  'pt', 'Foi desenvolvido um plano para pelo menos uma tecnologia emergente (por exemplo, AI, Wearables, Blockchain, IoT) para apoiar as metas de saúde pública, mas não está sendo implementado.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 3,  'pt', 'Existe um plano para pelo menos uma tecnologia emergente (por exemplo, AI, Wearables, Blockchain, IoT) para apoiar as metas de saúde pública. O(s) plano(s) identifica(m) os mecanismos de governança necessários para as tecnologias emergentes.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 4,  'pt', 'Um plano para uma ou mais tecnologias emergentes (por exemplo, AI, Wearables, Blockchain, IoT) para apoiar a saúde pública está sendo implementado, é financiado e os resultados estão sendo monitorados. Os mecanismos de governança necessários para as tecnologias emergentes estão em vigor.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 5,  'pt', 'Um plano para uma ou mais tecnologias emergentes (por exemplo, AI, Wearables, Blockchain, IoT) em apoio à saúde pública está sendo implementado, é financiado, os resultados estão sendo monitorados e o plano é mantido atualizado. Os mecanismos de governança estão em vigor e em uso.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32,-1,  'pt', 'Não disponível');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 1,  'pt', 'Estratégias e programas de saúde digital são desenvolvidos e implementados sem considerar as implicações de equidade e direitos humanos.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 2,  'pt', 'Estratégias e programas de saúde digital são desenvolvidos e implementados com consideração ad hoc de equidade e implicações de direitos humanos.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 3,  'pt', 'Estratégias e programas de saúde digital são desenvolvidos e implementados com consideração formal das implicações de equidade e direitos humanos, sem estratégia(s) para abordá-los.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 4,  'pt', 'Estratégias e programas de saúde digital são desenvolvidos e implementados com consideração formal das implicações de equidade e direitos humanos com estratégia(s) ad hoc para abordá-los.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 5,  'pt', 'O país está implementando e avaliando os efeitos de estratégias de saúde digital e soluções específicas de saúde digital com base em avaliações de impacto de equidade e direitos humanos. Existem estratégias documentadas para abordar as lacunas no acesso e resultados para diferentes grupos populacionais, incluindo mulheres, crianças e grupos marginalizados.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33,-1,  'pt', 'Não disponível');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 1,  'pt', 'Estratégias e intervenções de saúde digital são desenvolvidas e implementadas sem consideração de normas, papéis e relações de gênero.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 2,  'pt', 'Estratégias e intervenções de saúde digital são desenvolvidas e implementadas com consideração ad hoc e não sistemática de normas, papéis e relações de gênero.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 3,  'pt', 'Estratégias e programas de saúde digital são desenvolvidos e implementados com consideração sistemática das normas, papéis e relações de gênero sem as políticas ou estruturas de responsabilidade (sensíveis ao gênero).');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 4,  'pt', 'Estratégias e programas de saúde digital são desenvolvidos e implementados com consideração sistemática de normas, papéis e relações de gênero com estratégias específicas direcionadas a órgãos de governança, força de trabalho em saúde e clientes com mecanismos de responsabilidade (específicos de gênero).');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 5,  'pt', 'Estratégias, políticas e intervenções de saúde digital abordam a desigualdade de gênero e promovem mudanças progressivas na dinâmica de gênero com base em análises de gênero de rotina e avaliações de impacto (transformadoras de gênero).');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37,-1,  'pt', 'Não disponível');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 1,  'pt', 'A estratégia de saúde digital não existe ou existe e não está alinhada com a cobertura universal de saúde e não aborda nenhum dos principais componentes da cobertura universal de saúde, acesso, aceitação, qualidade e equidade.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 2,  'pt', 'A estratégia de saúde digital existe e está parcialmente alinhada com a cobertura universal de saúde, abordando apenas um componente central da cobertura universal de saúde, acesso, aceitação, qualidade e equidade.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 3,  'pt', 'A estratégia de saúde digital existe e está parcialmente alinhada com a cobertura universal de saúde, abordando dois ou mais componentes centrais da cobertura universal de saúde, acesso, aceitação, qualidade e equidade.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 4,  'pt', 'A estratégia de saúde digital existe e está totalmente alinhada com as metas de cobertura universal de saúde do país, mas não inclui métricas para avaliar a contribuição da saúde digital para as metas de cobertura universal de saúde.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 5,  'pt', 'A estratégia de saúde digital está totalmente alinhada com as metas de UHC do país e inclui métricas para avaliar a contribuição da saúde digital para as metas de UHC.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38,-1,  'pt', 'Não disponível');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 1,  'pt', 'O setor privado não participa e investe visivelmente nas atividades de saúde digital do país.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 2,  'pt', 'A participação e o investimento do setor privado nas atividades e investimentos de saúde digital do país são pontuais e limitados.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 3,  'pt', 'A participação e o investimento do setor privado nas atividades de saúde digital do país são sistemáticos, mas não atendem às necessidades do país.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 4,  'pt', 'A participação e o investimento do setor privado nas atividades de saúde digital do país são sistemáticos e atendem às necessidades do país.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 5,  'pt', 'O setor privado participa e investe nas atividades de saúde digital do país em um ambiente otimizado.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36,-1,  'pt', 'Não disponível');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 1,  'pt', 'Não há protocolos, políticas, estruturas ou processos aceitos que regem o uso de IA nos serviços de saúde.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 2,  'pt', 'Protocolos, políticas, estruturas ou processos aceitos que regem o uso de IA em serviços de saúde foram propostos e estão sendo revisados');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 3,  'pt', 'Protocolos, políticas, estruturas ou processos aceitos que regem o uso de IA em serviços de saúde foram aprovados, mas não foram totalmente implementados.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 4,  'pt', 'Protocolos, políticas, estruturas ou processos aceitos que regem o uso de IA em serviços de saúde foram implementados, mas não são aplicados de forma consistente.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 5,  'pt', 'Protocolos, políticas, estruturas ou processos aceitos que regem o uso de IA em serviços de saúde foram implementados e aplicados de forma consistente.');

INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34,-1,  'pt', 'Não disponível');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 1,  'pt', 'Não existe nenhum sistema xseguro de feedback do paciente.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 2,  'pt', 'Existe um sistema seguro de feedback do paciente para alguns serviços de saúde, mas está incompleto/parcialmente disponível, usado e mantido de forma irregular.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 3,  'pt', 'Um sistema de feedback seguro existe, está disponível e em uso ativo e inclui dados de <25% dos serviços de saúde relevantes e/ou localização geográfica. Está disponível para parte da população.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 4,  'pt', 'Um sistema de feedback seguro existe, está disponível e em uso ativo e inclui dados de 25-75% dos serviços de saúde relevantes e/ou localização geográfica. Está disponível para a maioria da população.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 5,  'pt', 'Existe um sistema de feedback seguro, está disponível em formatos acessíveis e em uso ativo e inclui dados de >75% dos serviços de saúde relevantes e/ou localização geográfica. Está disponível para 100% da população.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35,-1,  'pt', 'Não disponível');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 1,  'pt', 'Nenhuma contribuição de qualquer iniciativa de saúde digital para relatórios de rotina ou para tomada de decisão baseada em dados para gerenciamento de saúde da população.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 2,  'pt', 'Os sistemas digitais usados nos níveis distrital/estadual contribuem apenas para relatórios de saúde pública do país e tomada de decisões para a gestão da saúde da população.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 3,  'pt', 'Os sistemas digitais são usados em nível de estabelecimento ou comunidade e contribuem para os relatórios de saúde pública do país e para a tomada de decisões para o gerenciamento da saúde da população.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 4,  'pt', 'Os sistemas digitais são usados em instalações ou comunidades e por indivíduos e contribuem para os relatórios de saúde pública do país e para a tomada de decisões para a gestão da saúde da população.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 5,  'pt', 'Os sistemas digitais usados em todos os níveis, inclusive por indivíduos, contribuem para relatórios de saúde pública do país e tomadas de decisão oportunas para a gestão da saúde da população.');
