INSERT INTO master.health_indicators (indicator_id, name, definition, code, parent_id) VALUES (30,'Health is prioritized in national digital transformation and data governance policies', 'Do national digital transformation and data governance policies and approaches consider and address potential benefits and risks for public health and individual health?','2a',2);
INSERT INTO master.health_indicators (indicator_id, name, definition, code, parent_id) VALUES (37,'National digital strategy alignment with Universal Health Coverage (UHC) Core Components', 'Is the country’s national digital health strategy aligned with universal health coverage and/or UHC core components?','3a',3);
INSERT INTO master.health_indicators (indicator_id, name, definition, code, parent_id) VALUES (38,'Private sector participation and investments in digital health', 'Private sector participation and investments in digital health','4a',4);
INSERT INTO master.health_indicators (indicator_id, name, definition, code, parent_id) VALUES (36,'Protocol for regulating and certifying AI within health services', 'Are there protocols, policies, frameworks or accepted processes governing the use of AI within health systems, services and applications, particularly in relation to ethics, equity, safety, data integrity and quality of care?','7a',7);
INSERT INTO master.health_indicators (indicator_id, name, definition, code) VALUES (34,'Secure Patient Feedback Systems', 'Specifically, is there a secure Patient feedback system, available, accessible?','20');
INSERT INTO master.health_indicators (indicator_id, name, definition, code) VALUES (35,'Population health management contribution of digital health', 'Are current country digital health initiatives contributing to public health reporting and decision making?','21');
INSERT INTO master.health_indicators (indicator_id, name, definition, code) VALUES (31,'Readiness for emerging technologies adoption and governance', 'Is there a national plan specific to emerging technologies (e.g., AI, Wearables, Blockchain, IoT) to support public health goals?','22');
INSERT INTO master.health_indicators (indicator_id, name, definition, code) VALUES (32,'Diversity, Equity, and human rights analysis, planning and monitoring included in national digital health strategies and plans', 'Has the country assessed/adapted national digital health strategies from an equity and human rights perspective?','23');
INSERT INTO master.health_indicators (indicator_id, name, definition, code, parent_id) VALUES (33,'Gender considerations accounted for in digital health strategies and digital health governance', 'Does the country include gender considerations in the national digital health strategy or its digital health governance?','23a',23);

