update  master.health_indicators set rank = 1 , code = '1' where indicator_id = 1;
update  master.health_indicators set rank = 2 , code = '2'  where indicator_id = 2;
update  master.health_indicators set rank = 3 , code = '2a' , parent_id = 2 where indicator_id = 30;
update  master.health_indicators set rank = 4 , code = '3'  where indicator_id = 31;
update  master.health_indicators set rank = 5 , code = '4'  where indicator_id = 32;
update  master.health_indicators set rank = 6 , code = '4a' , parent_id = 4  where indicator_id = 33;
update  master.health_indicators set rank = 7 , code = '5'  where indicator_id = 3;
update  master.health_indicators set rank = 8  , code = '5a' , parent_id = 5 where indicator_id = 37;
update  master.health_indicators set rank = 9  , code = '6' where indicator_id = 4;
update  master.health_indicators set rank = 10 , code = '6a' , parent_id = 6 where indicator_id = 38;
update  master.health_indicators set rank = 11 , code = '7'  where indicator_id = 5;
update  master.health_indicators set rank = 12 , code = '8'  where indicator_id = 6;
update  master.health_indicators set rank = 13 , code = '9'  where indicator_id = 7;
update  master.health_indicators set rank = 14 , code = '9a' , parent_id = 9 where indicator_id = 36;
update  master.health_indicators set rank = 15 , code = '10'  where indicator_id = 8;
update  master.health_indicators set rank = 16 , code = '11'  where indicator_id = 9;
update  master.health_indicators set rank = 17 , code = '12'  where indicator_id = 10;
update  master.health_indicators set rank = 18 , code = '13' where indicator_id = 11;
update  master.health_indicators set rank = 19 , code = '14'  where indicator_id = 12;
update  master.health_indicators set rank = 20 , code = '15'  where indicator_id = 13;
update  master.health_indicators set rank = 21 , code = '16' where indicator_id = 14;
update  master.health_indicators set rank = 22 , code = '17'  where indicator_id = 15;
update  master.health_indicators set rank = 23 , code = '18' where indicator_id = 16;
update  master.health_indicators set rank = 24 , code = '19' where indicator_id = 17;
update  master.health_indicators set rank = 25 , code = '20' where indicator_id = 18;
update  master.health_indicators set rank = 26 , code = '21' where indicator_id = 19;
update  master.health_indicators set rank = 27 , code = '21a' , parent_id = 21 where indicator_id = 27;
update  master.health_indicators set rank = 28 , code = '21b' , parent_id = 21 where indicator_id = 28;
update  master.health_indicators set rank = 29 , code = '21c' , parent_id = 21 where indicator_id = 29;
update  master.health_indicators set rank = 30 , code = '22' where indicator_id = 34;
update  master.health_indicators set rank = 31 , code = '23' where indicator_id = 35;
