INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30,-1,  'es', 'No disponible');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 1,  'es', 'Las políticas nacionales de transformación digital y gobernanza de datos no incluyen beneficios y riesgos potenciales para la salud pública o los resultados de salud individual.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 2,  'es', 'Las políticas nacionales de gobernanza de datos y transformación digital incluyen beneficios y riesgos potenciales para la salud pública o los resultados de salud individuales de manera ad hoc.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 3,  'es', 'Las políticas nacionales de transformación digital y gobernanza de datos incluyen sistemáticamente los posibles beneficios y riesgos para la salud pública o los resultados de salud individuales, pero no tienen estrategias para abordarlos.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 4,  'es', 'Las políticas nacionales de transformación digital y gobernanza de datos incluyen sistemáticamente los posibles beneficios y riesgos para la salud pública o los resultados de salud individuales y tienen algunas estrategias para abordarlos que aún no se han implementado.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 30, 5,  'es', 'Todas las políticas relevantes de transformación digital y gobernanza de datos consideran completamente los beneficios y riesgos potenciales para los sistemas de salud, los determinantes de la salud y los resultados de salud individuales (incluidos los niños, las mujeres y los grupos vulnerables) y tienen estrategias multisectoriales que se implementan por completo.');

INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31,-1,  'es', 'No disponible');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 1,  'es', 'No existe un plan de tecnologías emergentes ( ej., IA, Wearables, Blockchain, IoT) en apoyo de los objetivos de salud pública.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 2,  'es', 'Se desarrolló un plan para al menos una tecnología emergente (por ejemplo, IA, Wearables, Blockchain, IoT) para respaldar los objetivos de salud pública, pero no se está implementando.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 3,  'es', 'Existe un plan para al menos una tecnología emergente (por ejemplo, IA, Wearables, Blockchain, IoT) para respaldar los objetivos de salud pública. Los planes identifican los mecanismos de gobernanza necesarios para las tecnologías emergentes.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 4,  'es', 'Se está implementando, financiando y monitoreando los resultados un plan para una o más tecnologías emergentes ( ej. IA, Wearables, Blockchain, IoT) para apoyar la salud pública. Existen los mecanismos de gobernanza necesarios para las tecnologías emergentes.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 31, 5,  'es', 'Se está implementando y financiando un plan para una o más tecnologías emergentes (por ejemplo, AI, Wearables, Blockchain, IoT) en apoyo de la salud pública, se están monitoreando los resultados y se mantiene actualizado el plan. Los mecanismos de gobernanza están establecidos y en uso.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32,-1,  'es', 'No disponible');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 1,  'es', 'Las estrategias y programas de salud digital se desarrollan e implementan sin tener en cuenta las implicaciones de equidad y derechos humanos.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 2,  'es', 'Las estrategias y programas de salud digital se desarrollan e implementan considerando las implicaciones de equidad y derechos humanos ad hoc.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 3,  'es', 'Las estrategias y programas de salud digital se desarrollan e implementan considerando formalmente las implicaciones de equidad y derechos humanos sin estrategia(s) para abordarlas.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 4,  'es', 'Las estrategias y programas de salud digital se desarrollan e implementan considerando formalmente las implicaciones de equidad y derechos humanos con estrategias ad hoc para abordarlas.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 32, 5,  'es', 'El país está implementando y evaluando los efectos de estrategias de salud digital y soluciones específicas de salud digital basadas en evaluaciones de impacto en equidad y derechos humanos. Existen estrategias documentadas para abordar las brechas en el acceso y los resultados para diferentes grupos de población, incluidas mujeres, niños y grupos marginados.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33,-1,  'es', 'No disponible');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 1,  'es', 'Las estrategias e intervenciones de salud digital se desarrollan e implementan sin tener en cuenta las normas, roles y relaciones de género.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 2,  'es', 'Las estrategias e intervenciones de salud digital se desarrollan e implementan con consideración ad hoc y no sistemática de las normas, roles y relaciones de género.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 3,  'es', 'Las estrategias y programas de salud digital se desarrollan e implementan con consideración sistemática de las normas, roles y relaciones de género sin las políticas o estructuras para la rendición de cuentas (sensible al género).');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 4,  'es', 'Las estrategias y programas de salud digital se desarrollan e implementan considerando sistemáticamente las normas, roles y relaciones de género con estrategias específicas dirigidas a los órganos de gobierno, el personal de salud y los clientes con mecanismos de rendición de cuentas (específicos de género).');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 33, 5,  'es', 'Las estrategias, políticas e intervenciones de salud digital abordan la desigualdad de género y fomentan un cambio progresivo en la dinámica de género basado en análisis de género de rutina y evaluaciones de impacto (transformación de género).');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37,-1,  'es', 'No disponible');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 1,  'es', 'La estrategia de salud digital no existe o existe y no está alineada con CSU y no aborda ninguno de los componentes centrales de CSU de cobertura, acceso, aceptación, calidad y equidad.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 2,  'es', 'La estrategia de salud digital existe y está parcialmente alineada con la CSU, abordando sólo un componente central de la CSU de cobertura, acceso, aceptación, calidad y equidad.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 3,  'es', 'La estrategia de salud digital existe y está parcialmente alineada con la CSU, abordando dos o más componentes básicos de la CSU de cobertura, acceso, aceptación, calidad y equidad.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 4,  'es', 'La estrategia de salud digital existe y está totalmente alineada con los objetivos de CSU del país, pero no incluye métricas para evaluar la contribución de la salud digital a los objetivos de CSU.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 37, 5,  'es', 'La estrategia de salud digital está completamente alineada con los objetivos de CSU del país e incluye métricas para evaluar la contribución de la salud digital hacia los objetivos de CSU.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38,-1,  'es', 'No disponible');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 1,  'es', 'El sector privado no participa ni invierte visiblemente en las actividades de salud digital del país.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 2,  'es', 'La participación e inversión del sector privado en las actividades e inversiones en salud digital del país es ad-hoc y limitada.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 3,  'es', 'La participación e inversión del sector privado en las actividades de salud digital del país es sistemática pero no satisface las necesidades del país.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 4,  'es', 'La participación e inversión del sector privado en las actividades de salud digital del país es sistemática y responde a las necesidades del país.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 38, 5,  'es', 'El sector privado participa e invierte en las actividades de salud digital del país en un entorno optimizado.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36,-1,  'es', 'No disponible');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 1,  'es', 'No existen protocolos, políticas, marcos o procesos aceptados que rijan el uso de la IA en los servicios de salud.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 2,  'es', 'Se han propuesto y se están revisando protocolos, políticas, marcos o procesos aceptados que rigen el uso de la IA en los servicios de salud.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 3,  'es', 'Se aprobaron protocolos, políticas, marcos o procesos aceptados que rigen el uso de la IA en los servicios de salud, pero no se implementaron por completo.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 4,  'es', 'Se han implementado protocolos, políticas, marcos o procesos aceptados que rigen el uso de IA en los servicios de salud, pero no se aplican de manera consistente.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 36, 5,  'es', 'Los protocolos, las políticas, los marcos o los procesos aceptados que rigen el uso de la IA en los servicios de salud se han implementado y se aplican de manera consistente.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34,-1,  'es', 'No disponible');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 1,  'es', 'No existe un sistema seguro de retroalimenta-ción del paciente.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 2,  'es', 'Existe un sistema seguro de retroalimentación del paciente para algunos servicios de salud, pero está incompleto/parcialmente disponible, se usa y se mantiene de manera irregular.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 3,  'es', 'Existe un sistema de retroalimentación seguro, está disponible y en uso activo e incluye datos de <25% de los servicios de salud y/o ubicación geográfica relevantes. Está disponible para una parte de la población.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 4,  'es', 'Existe un sistema de retroalimentación seguro, está disponible y en uso activo e incluye datos del 25-75% de los servicios de salud relevantes y/o ubicación geográfica. Está disponible para la mayoría de la población.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 34, 5,  'es', 'Existe un sistema de retroalimentación seguro, está disponible en formatos accesibles y en uso activo e incluye datos de >75% de los servicios de salud y/o ubicación geográfica relevantes. Está disponible para el 100% de la población.');


INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35,-1,  'es', 'No disponible');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 1,  'es', 'No existe ninguna contribución de alguna iniciativa de salud digital a los informes de rutina o a la toma de decisiones basada en datos para la gestión de la salud de la población.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 2,  'es', 'Los sistemas digitales utilizados a nivel de distrito/estado solo contribuyen a los informes de salud pública del país y a la toma de decisiones para la gestión de la salud de la población.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 3,  'es', 'Los sistemas digitales se utilizan a nivel de establecimiento o comunidad y contribuyen a la elaboración de informes de salud pública del país y a la toma de decisiones para la gestión de la salud de la población.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 4,  'es', 'Los sistemas digitales son utilizados en establecimientos o comunidades y por individuos y contribuyen a la elaboración de informes de salud pública del país y a la toma de decisiones para la gestión de la salud de la población.');
INSERT INTO i18n.score_definition(indicator_id, score, language_id, definition) VALUES( 35, 5,  'es', 'Los sistemas digitales utilizados en todos los niveles, incluso por parte de las personas, contribuyen a la notificación oportuna de la salud pública del país y a la toma de decisiones para la gestión de la salud de la población.');
