name: Java CI with Gradle

on:
  push:
    branches: [ "Actions_setup" ]
  pull_request:
    branches: [ "Actions_setup" ]
    
env:
  SPRING_PROFILES_ACTIVE: test
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: check out code
         uses: actions/checkout@v3

       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'

       - name: grant permissions
         run : chmod +x gradlew
         
       - name: Test with H2
         run: ./gradlew test

       - name: build action
         run : ./gradlew build
